<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Deployables\1.1\**" />
    <Content Remove="Deployables\1.1\**" />
    <EmbeddedResource Remove="Deployables\1.1\**" />
    <None Remove="Deployables\1.1\**" />
    <None Remove="AppCode\Commands\FormularyCommand - Copy.Create.cs.bkp" />
    <None Remove="AppCode\Commands\FormularyCommand - Copy.Edit.cs.bkp" />
    <None Remove="AppCode\Commands\FormularyCommand - Copy.FileImport.cs.bkp" />
    <None Remove="AppCode\Commands\FormularyCommand - Copy.Import.cs.bkp" />
    <None Remove="Controllers\Utility\FormularyUtilController.cs.old" />
    <None Remove="RestSharp" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="AppCode\Queries\FormularyRuleBasedQueryProcessor\RuleBoundAMPFormularyBuilder_copy.cs.tbr" />
    <None Remove="AppCode\Queries\FormularyRuleBasedQueryProcessor\RuleBoundVMPFormularyBuilder - Copy.cs.tbr" />
    <None Remove="AppCode\Queries\FormularyRuleBasedQueryProcessor\RuleBoundVTMFormularyBuilder - Copy.cs.tbr" />
    <None Remove="AppCode\Validators\CreateFormularyRequestValidator.cs.bkp" />
    <None Remove="AppCode\Validators\EditFormularyRequestValidator.cs.bkp" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="AppCode\Queries\FormularyRuleBasedQueryProcessor\RuleBoundAMPFormularyBuilder_copy.cs.tbr" />
    <Compile Include="AppCode\Queries\FormularyRuleBasedQueryProcessor\RuleBoundVMPFormularyBuilder - Copy.cs.tbr" />
    <Compile Include="AppCode\Queries\FormularyRuleBasedQueryProcessor\RuleBoundVTMFormularyBuilder - Copy.cs.tbr" />
    <Compile Include="AppCode\Validators\CreateFormularyRequestValidator.cs.bkp" />
    <Compile Include="AppCode\Validators\EditFormularyRequestValidator.cs.bkp" />
    <Compile Include="Controllers\Utility\FormularyUtilController.cs.old" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.1" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="CompareNETObjects" Version="4.83.0" />
    <PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.28.0" />
    <PackageReference Include="Elastic.Apm.SerilogEnricher" Version="8.11.1" />
    <PackageReference Include="Elastic.CommonSchema.Serilog" Version="8.11.1" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
    <PackageReference Include="Interneuron.Caching" Version="6.0.0" />
    <PackageReference Include="Interneuron.FDBAPI.Client" Version="4.0.0" />
    <PackageReference Include="Interneuron.Web.Exceptions" Version="6.0.0" />
    <PackageReference Include="Interneuron.Web.Logger" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="6.6.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.6.2" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.4.3" />
    <PackageReference Include="RestSharp" Version="111.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Model\Interneuron.Terminology.Model.csproj" />
    <ProjectReference Include="..\Repository\Interneuron.Terminology.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AppCode\DSLs\" />
    <Folder Include="Deployables\ETLJobs_Source\" />
  </ItemGroup>

</Project>
