<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Interneuron.Terminology.Backgroundservice-CCFBB31B-2ACA-4FCD-9AAC-D336123FC420</UserSecretsId>
    <OutputType>exe</OutputType>
    <PublishSingleFile Condition="'$(Configuration)' == 'Release'">true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AppCode\Handlers\DeltaIdentificationHandler.cs.bkp" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="AppCode\Handlers\DeltaIdentificationHandler.cs.bkp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="CompareNETObjects" Version="4.83.0" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.28.0" />
    <PackageReference Include="Interneuron.Common" Version="6.0.0" />
    <PackageReference Include="Interneuron.FDBAPI.Client" Version="3.0.0" />
    <PackageReference Include="Interneuron.Web.Logger" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <!--<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
    <PackageReference Include="Polly" Version="8.4.1" />
    <PackageReference Include="Polly.Contrib.WaitAndRetry" Version="1.1.1" />
    <PackageReference Include="RestSharp" Version="111.4.0" />
    <PackageReference Include="Serilog" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Model\DomainModels\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Deployment\WindowsService.DMDBrowser.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Deployment\WindowsService.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
